### ISSUE TITLE
System.Management.ManagementException: 'Not supported '

### ISSUE THREAD

**Issue by BeansSi** [blackholeearth/Win10_BrightnessSlider#102]
I have been trying your code on visual studio. but i keep getting this error when i try to test run the program:

System.Management.ManagementException: 'Not supported '

```
System.Management.ManagementException
  HResult=0x80131501
  Message=Not supported 
  Source=System.Management
  StackTrace:
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Win10_BrightnessSlider.Form1.GetBrightness() in C:\Users\********\Downloads\Win10_BrightnessSlider-master\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs:line 201
   at Win10_BrightnessSlider.Form1.UpdateStatesOnGuiControls() in C:\Users\********\Downloads\Win10_BrightnessSlider-master\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs:line 101
   at Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\********\Downloads\Win10_BrightnessSlider-master\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs:line 56
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by blackholeearth** [comment]
Duplicate . Readme source
