### ISSUE TITLE
Not working On Monitor over DP port and HDR enabled

### ISSUE THREAD

**Issue by Peke** [blackholeearth/Win10_BrightnessSlider#143]
Not working On Monitor over DP port and HDR enabled :( Win 10 2H22 Radeon 580+LC-Power LC-M32-QHD-165-C-K+HDR1000 Enabled

16.4.2023. 19:03:09 ==>  Caller(File,Member,Line): wmiMonFn.cs, SetBrightness, 48 
System.Management.ManagementException: Not supported 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Win10_BrightnessSlider.wmiMonFn.SetBrightness(Byte value, String wmi_InstanceName)

**Comment by blackholeearth** [comment]
Try 3nable ddci 7n you monitor settings.

https://github.com/blackholeearth/Win10_BrightnessSlider/blob/master/enable%20ddc-ci.jpg?raw=true

**Comment by blackholeearth** [comment]
Update monitor driver   driver booster.

* Monitor and * display card
