### ISSUE TITLE
Unhandled Exception has occurred in your application. StartIndex cannot be less that zero. Parameter name: startIndex

### ISSUE THREAD

**Issue by kstarks17** [blackholeearth/Win10_BrightnessSlider#26]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Win10_BrightnessSlider.RichInfoScreen.GetWmiMonitorID_by_TargetDeviceName(List`1 WMIMonitorIDs, DISPLAYCONFIG_TARGET_DEVICE_NAME dc_tarDevName)
   at Win10_BrightnessSlider.RichInfoScreen.Get_RichInfo_Screen()
   at Win10_BrightnessSlider.Form1.RePopulateSliders()
   at Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()

  
[this much suffices]

**Comment by kstarks17** [comment]
I get the logo on the toolbar but have no ability to change the brightness and nothing pops up when right clicked.

**Comment by blackholeearth** [comment]
https://github.com/blackholeearth/Win10_BrightnessSlider/releases   check 1.7.3

**Comment by kstarks17** [comment]
The slider is now showing up but is initially showing a value of -1 no matter where I leave it. Also, it is not actually changing the brightness at all. 

Right-click is showing the menu properly.

**Comment by blackholeearth** [comment]
ok use last working one ill mark them as unstable

**Comment by kstarks17** [comment]
Got it working. Had to detect monitor as well as update my monitor drivers. Cheers. Great app, great dev.

**Comment by blackholeearth** [comment]
good to hear.   **version 1.7.4  presses   "detect monitor"  internally for you** . did you try that.  
 on older version on every pc restart you have to  press "detect monitor" by yourself.
