### ISSUE TITLE
Add option to assign keyboard shortcuts

### ISSUE THREAD

**Issue by tliebig** [blackholeearth/Win10_BrightnessSlider#4]
Quite a bit of Sony Vaio laptops cannot change their brightness via keyboard on WIN10 since to some customization. Drivers from Sony are only provided up to Win 8.1. 

Having the option to manually assign Brightness_UP and Brightness_DOWN keyboard shortcuts would help mitigate the issue, since the slider itself works perfectly on my Vaio VGN-SR51MF.

Any chance that you could add this option?

**Comment by Flionwall** [comment]
Better yet have it work with the brightness control buttons.  I'm trying to get X-Mouse to control the brightness on my PC.

**Comment by blackholeearth** [comment]
Shortcut possible ,
but accessing fn key is not possible by c#
__________
Desktop lighter app changes gamma not backlight.  Your eyes still hurt.

**Comment by aporojan** [comment]
Shortcut would be very useful and if it's possible to let us choose the shortcut it would be amazing. 

Also it doesn't play very well with the "change brightness automatically when lighting changes" on Windows 10 (it still works but there is a range, in my case 0-50, in which nothing happens but between 50 and 100 the brightness does change).

**Comment by blackholeearth** [comment]
"Disable widows adaptive brightness " İs another issue. You have to disable it by yourselfff.

**Comment by sonatamartica** [comment]
so any luck with adding hotkeys? My desktop keyboard doesnt have brightness keys so copying desktop lighters keys would work well im guessing?

**Comment by harshmandan** [comment]
@blackholeearth Any update good sire?

**Comment by inugami-doo** [comment]
Dont work for me, log 3/16/2022 8:43:10 PM ==>  Caller(File,Member,Line): wmiMonFn.cs, GetBrightness, 85 
System.Management.ManagementException: Not supported 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Win10_BrightnessSlider.wmiMonFn.GetBrightness(String wmi_InstanceName)

**Comment by hotzen** [comment]
Can you listen to the standard windows brightness events, that notebooks emit via their Fn-keys, instead of globally listening to arbitrary shortcuts, to listen to windows standard events?
Perhaps by querying https://learn.microsoft.com/en-us/windows/win32/wmicoreprov/wmimonitorbrightness?redirectedfrom=MSDN as per https://stackoverflow.com/a/1768344/234073 ?

Thanks a bunch for this tool, finally can simply control my monitors brightness

**Comment by blackholeearth** [comment]
@hotzen afaik fn keys are not passed to os.

They ar handled at hardware level.
Or we have to vendor specific dlls. Thats complicated stuff no-one  bothers with it..

Its easier to listen non-fn keys..
